- components/Modal/Modal.tsx
- components/Player/CoverArt/CoverArt.tsx
- components/Player/ForwardButton/ForwardButton.tsx
- components/Player/NextButton/NextButton.tsx
- components/Player/PlayButton/PlayButton.tsx
- components/Player/Player.tsx
- components/Player/PlayerProgress/PlayerProgress.tsx
- components/Player/Playlist/Playlist.module.scss
- components/Player/Playlist/Playlist.tsx
- components/Player/PreviousButton/PreviousButton.tsx
- components/Player/ReplayButton/ReplayButton.tsx
- interfaces/contexts/IPlayerContext.ts
- interfaces/embed/IEmbedConfig.ts
- interfaces/states/player/IPlayerState.ts
- lib/generate/string/generateEmbedUrl.ts
- lib/parse/config/parseEmbedParamsToConfig.spec.ts
- lib/parse/config/parseEmbedParamsToConfig.ts
- pages/embed.tsx
- states/player/Player.reducer.spec.ts
- states/player/Player.reducer.ts
- styles/Embed.module.scss
Closes #33 
- Adds hotkey controls
- Spacebar: Toggle play/pause or trigger focused button
- J : Seek back 10 seconds
- K : Toggle play/pause
- L : Seek forward 10 seconds
- Left : Seek back 5 seconds
- Right : Seek forward 5 seconds
- Comma : Seek back 1/30th second
- Period : Seek forward 1/30th second
- Home : Seek to start
- End : Seek to end
- 1-9: Seek to percentage of pressed key (multiples of 10)
- 0 : Seek to start
- [ : Previous track
- ] : Next track
- M : Mute volume
- Up : Increase volume by 5%
- Down : Decrease volume by 5%
- Adjusted when controls layout change while cover art is shown.
> ...then...
> #33: Hotkey control events

- components/IconButton/IconButton.module.scss
- components/Player/CopyLinkButton/CopyLinkButton.tsx
- components/Player/CopyLinkButton/index.ts
- components/Player/ShareEmailButton/ShareEmailButton.tsx
- components/Player/ShareEmailButton/index.ts
- components/Player/ShareFacebookButton/ShareFacebookButton.tsx
- components/Player/ShareFacebookButton/index.ts
- components/Player/ShareTwitterButton/ShareTwitterButton.tsx
- components/Player/ShareTwitterButton/index.ts
- package.json
- pages/embed.tsx
- styles/Embed.module.scss
- yarn.lock
Closes #14 
- add share buttons for fb, tw, and email
- add copy link button
- add fa icon styling to icon button
> ...then...
> #14: Share modal buttons

- lib/generate/string/generateAudioUrl.spec.ts
- lib/generate/string/generateAudioUrl.ts
- lib/parse/data/parseAudioData.spec.ts
- lib/parse/data/parseAudioData.ts
- lib/parse/data/parseEmbedData.spec.ts
- lib/parse/data/parseEmbedData.ts
Closes #40 
- Adds `_from=play.prx.org` to audio URL's that do not already have a `_from` param.
> ...then...
> #40: Add `_from` param to audio URL's

- components/Modal/Modal.module.scss
- components/Player/Player.tsx
- components/Player/PlayerThumbnail/PlayerThumbnail.tsx
- components/Player/Playlist/Playlist.tsx
- components/PrxImage/PrxImage.module.scss
- components/PrxImage/PrxImage.tsx
- lib/parse/data/parseAudioData.ts
- lib/parse/data/parseEmbedData.spec.ts
- lib/parse/data/parseEmbedData.ts
- pages/embed.tsx
- styles/Embed.module.scss
Closes #44 
- Player layout should change more smartly, favoring layouts that allow control and menu buttons to be visible at more screen sizes.
> ...or...
> ...then...
> SIDE QUEST: Use the preview deploy domain to see how layouts work in your SE source clone.
> #44: Content aware layout switching

- components/BackgroundImage/BackgroundImage.module.scss
- components/BackgroundImage/BackgroundImage.tsx
- components/Player/CoverArt/CoverArt.tsx
- components/Player/Player.tsx
- components/Player/PlayerThumbnail/PlayerThumbnail.tsx
- components/Player/Playlist/Playlist.module.scss
- pages/embed.tsx
- background image tint darker when backdrop blur not supported
- remove content flash on load
- catch audio play errors
- playlist highlight contained to tack button
- modal container not rendered till modal shown
> ...then...
> hotfix: tweaks for firefox

- pages/index.tsx
Closes #82
- `us` example uses correct param
- remove duplicate `ge` docs
> ...then...
> 82: Documentation fixes

- components/Player/Player.tsx
Closes #81
- Hotkeys will not trigger actions when modifier keys are also pressed.
> ...then...
> 81: Don't fire hotkey events when modifier keys are pressed

- interfaces/error/IPageError.ts
- interfaces/error/index.ts
- interfaces/page/IEmbedPageProps.ts
- interfaces/page/IListenPageProps.ts
- interfaces/page/IPageProps.ts
- interfaces/page/index.ts
- lib/parse/data/parseEmbedData.ts
- pages/embed.tsx
- pages/listen/index.tsx
Closes #86 
- rss proxy errors return 400 response
- show error message for bad feed URL's
- add same error handling and messaging to listen page
> ...then...
> 86: Better RSS proxy error handling

- lib/generate/string/generateAudioUrl.spec.ts
- lib/generate/string/generateAudioUrl.ts
Closes #91 
- When parsing RSS enclosure URL's, ensure it gets a protocol.
> 91: ensure audio url has protocol

- assets/svg/icons/FileDownload.svg
- components/Player/FileDownloadButton/FileDownloadButton.tsx
- components/Player/FileDownloadButton/index.ts
- components/Player/PlayerShareMenu/PlayerShareMenu.tsx
Closes #93 
- Adds a `download mp3 file` button onto embed player in pop-out modal's share menu.
Note that PRX audio will trigger a direct download, third party audio will open a new media player tab where the file can be saved.
> Adds 'Download' button onto embed player share menu

- interfaces/data/IRssPodcast.ts
- lib/parse/data/parseEmbedData.spec.ts
- lib/parse/data/parseEmbedData.ts
Closes #100 
- Corrects the attribute name to `valueRecpients`
> ...then...
> Make valueRecipients plural

- interfaces/data/IRssItem.ts
- lib/fetch/rss/fetchRssFeed.ts
- lib/parse/data/parseRssItems.spec.ts
- lib/parse/data/parseRssItems.ts
- yarn.lock
Co-authored-by: Alexa M. <a-maci29@users.noreply.github.com>
Closes #104 
- adds step for RSS item parser to check if a feed has `itunes:type` set to serial, then sort items by season and episode in ascending order.
> ...then...
> 104: Serial feed sorting

- lib/parse/config/parseAccentColorParam.spec.ts
- lib/parse/config/parseAccentColorParam.ts
- lib/parse/config/parseEmbedParamsToConfig.ts
- lib/parse/config/parseListenParamsToConfig.ts
Closes #107 
- bad accent color input should not cause 5XX errors
- add support for 3 char HEX colors
> ...then...
> 107: Add accent color param parser

- components/PrxImage/PrxImage.tsx
- lib/fetch/rss/decoratePodcast.spec.ts
- lib/fetch/rss/decoratePodcast.ts
- lib/fetch/rss/fetchRssFeed.ts
Closes #113
- Filter `podcast:value` items to first item with `type = 'webmonetization'` and `method = 'ILP'`, then use that in parsed feed data.
- fixes a bug where images from a a third party server would not un-blur when loaded.
> ...or...
> ...then...
> 113: Parse multiple podcast value

- components/Listen/Listen.tsx
- components/ThemeVars/ThemeVars.tsx
- memo render of playlist element
- don't render playlist element in episode view
> ...then...
> HOTFIX: Improve play/pause in episode view

- components/Player/PlayerProgress/PlayerProgress.module.scss
- Fix progress bar being displayed with 0px width
> ...then...
> HOTFIX: Progress bar should not collapse in a flex parent

- lib/parse/data/parseRssItems.spec.ts
- lib/parse/data/parseRssItems.ts
- pages/listen/index.tsx
- parser RSS items should no longe include `undefined` item in resulting array
- listen page should not attempt to find an episode if no episodes exist from rss parse
> HOTFIX: 500 on `/listen` page when filter options result in no playlist items

- components/Embed/Embed.tsx
- components/Player/Player.tsx
- components/Player/PlayerShareMenu/PlayerShareMenu.tsx
- interfaces/config/IEmbedConfig.ts
- interfaces/data/IAudioData.ts
- lib/parse/data/parseEmbedData.spec.ts
- lib/parse/data/parseEmbedData.ts
- Adds support for a `uap` parameter that will be used for playback.
- Removes `isPrivate` prop from embed config and related logic. No longer required.
> ...then...
> Embed config audio preview url

- pages/preview.tsx
Closes #128 
- Broadens condition to allow origins ending with `.prx.org`, `.prx.tech`, or `.prx.test`
> 128: Allow any prx subdomain to send post messages to preview page

- lib/parse/data/parseRssItems.spec.ts
- lib/parse/data/parseRssItems.ts
- Update RSS item parser too filter out items missing enclosure data.
> ...then...
> HOTFIX: handle RSS items missing enclosure

- lib/fetch/rss/RssProxyError.ts
- lib/fetch/rss/fetchRssFeed.ts
- lib/fetch/rss/fetchRssProxy.ts
- pages/embed.tsx
- Updates embed route to fetch RSS data via the app's RSS proxy API endpoint
- Updates embed route to not cache 400 error responses
> ...then...
> HOTFIX: Embed RSS fetch via proxy API

- components/Player/CoverArt/CoverArt.tsx
- components/Player/PlayerThumbnail/PlayerThumbnail.tsx
- components/PrxImage/PrxImage.module.scss
- components/PrxImage/PrxImage.tsx
- yarn.lock
Closes #147 
- fix images with blur transition defaulting to blurred in Safari
- forward ref as HTMLImageElement
- cover art component image ref
- player thumbnail component image ref
> ...then...
> 147: Playlist thumbnails collapsing in Safari

- Dockerfile
- package.json
- yarn.lock
- lock sharp to 0.32.6 (See https://community.contentstack.com/questions-conversations-38/troubleshoot-nextjs-image-optimization-not-working-on-contentstack-launch-483#:~:text=NextJS%20requires%20installing%20the%20sharp,of%20sharp%20(%3E%3D%200.33.)
- remove setting NEXT_SHARP_PATH from Dockerfile
> ...then...
> If you run `yarn start:standalone` images should still be optimized, but app will be broken since some static assets such as css and js may not load. Still looking into how to properly startup standalone server locally.
> build: lock sharp to 0.32.6

- .vscode/settings.json
- components/IconButton/IconButton.tsx
- components/Listen/Episode/Episode.module.scss
- components/Listen/Episode/Episode.tsx
- components/Listen/EpisodeList/EpisodeCard/EpisodeCard.module.scss
- components/Listen/EpisodeList/EpisodeCard/EpisodeCard.tsx
- components/Listen/EpisodeList/EpisodeList.module.scss
- components/Listen/FooterPlayer/FooterPlayer.module.scss
- components/Listen/FooterPlayer/FooterPlayer.tsx
- components/Listen/Listen.module.scss
- components/Listen/Listen.tsx
- components/Player/FileDownloadButton/FileDownloadButton.tsx
- interfaces/data/IAudioData.ts
- lib/parse/data/parseAudioData.spec.ts
- lib/parse/data/parseAudioData.ts
- package.json
- yarn.lock
Closes #127
Closes #155 
- add download link to playlist items
- add download link to episode header
- fix clipping of title text on episode view
- add fileSize to audio data
- add download prop to icon button component
- move cc button between progress bar and settings button
- improve layout of floating elements:
- player
- mobile playlist header
- mobile episode header
> ...then...
> 127: Add download links to listen page

- components/Player/Player.tsx
- pages/api/proxy/transcript/index.ts
- yarn.lock
Closes #159 
- add `x-subrip` to srt detection in transcript proxy
- add `x-subrip` to srt conversion check in Player
> ...or...
> ...then...
> 159: Update SRT transcript detection to include `application/x-subrip` content type

- Dockerfile
Increases the `keepAliveTimeout` of the Node server to 10 seconds (up from default of 5 seconds). Hopefully this will prevent so many of the `ECONNRESET` errors we have been seeing.
> Set KEEP_ALIVE_TIMEOUT to 10 seconds

- components/Listen/EpisodeList/EpisodeCard/EpisodeCard.tsx
- yarn.lock
EpisodeCard download links were using Next's Link component, which cleans up double forward slashes (`//`). Fine for most links, but not for our audio links which could have any number of prefixed services chains, like podtrac and chrt.fm. If the chained prefix includes the protocol, the link will break if the double slashes are converted to a single slash.
This PR changes the EpisodeCard download link to use a regular `<a>` tag instead of the Link component. 
> ...then...
> Change EpisodeCard download link to <a> tag

- next.config.js
- yarn.lock
- adds Cache-Control headers to `/listen' route that match those used on `/e` route.
> ...then...
> config(next): add cache-control header w/ max-age to listen route

- next-logger.config.js
- package.json
- yarn.lock
- adds `pino-pretty` to logger in dev env
> ...then...
> Improve readability of logged messages in dev env
